// Code generated by ent, DO NOT EDIT.

package dbx

import (
	"context"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

type multiDriver struct {
	r, w dialect.Driver
}

var _ dialect.Driver = (*multiDriver)(nil)

func NewMultiDriver(r, w dialect.Driver) dialect.Driver {
	return &multiDriver{
		r: r,
		w: w,
	}
}

func (d *multiDriver) Dialect() string {
	return d.r.Dialect()
}

func (d *multiDriver) Query(ctx context.Context, query string, args, v any) error {
	return d.r.Query(ctx, query, args, v)
}

func (d *multiDriver) Exec(ctx context.Context, query string, args, v any) error {
	return d.w.Exec(ctx, query, args, v)
}

func (d *multiDriver) Tx(ctx context.Context) (dialect.Tx, error) {
	return d.w.Tx(ctx)
}

func (d *multiDriver) BeginTx(ctx context.Context, opts *sql.TxOptions) (dialect.Tx, error) {
	return d.w.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
}

func (d *multiDriver) Close() error {
	rerr := d.r.Close()
	werr := d.w.Close()
	if rerr != nil {
		return rerr
	}
	if werr != nil {
		return werr
	}
	return nil
}
