// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"github.com/aesoper101/kratos-monorepo-layout/app/helloworld/internal/data/ent/schema","Package":"github.com/aesoper101/kratos-monorepo-layout/app/helloworld/internal/data/ent/schemagen","Schemas":[{"name":"User","config":{"Table":""},"fields":[{"name":"username","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"position":{"Index":0,"MixedIn":false,"MixinIndex":0},"comment":"姓"}]}],"Features":["privacy","entql","schema/snapshot","sql/modifier","sql/schemaconfig","namedges","sql/lock"]}`
