// Code generated by protoc-gen-go-validate. DO NOT EDIT.

package v1

import (
	context "context"
	validator "github.com/aesoper101/protoc-gen-govalidate/validator"
)

var (
	_helloRequestRule = map[string]string{
		"Name": "required,startswith=as",
	}
)

func init() {
	validator.Validator().RegisterStructValidationMapRules(_helloRequestRule, HelloRequest{})
}

func (x *HelloRequest) Validate() error {
	return validator.Validator().Struct(x)
}

func (x *HelloRequest) ValidateCtx(ctx context.Context) error {
	return validator.Validator().StructCtx(ctx, x)
}
